# Generated by Django 5.1.2 on 2024-10-29 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_sale_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='stock_error',
            field=models.BooleanField(default=False),
        ),
    ]
