# Generated by Django 5.1.2 on 2026-09-11 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_sale_payment_method_sale_user_stockmovement'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Costo de adquisición o costo base', max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='item_type',
            field=models.CharField(choices=[('PRODUCT', 'Producto de Reventa'), ('SERVICE', 'Servicio / Preparado')], default='PRODUCT', max_length=10),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Costo unitario congelado al momento de la venta', max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Precio de venta al público', max_digits=10),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='price',
            field=models.DecimalField(decimal_places=2, editable=False, help_text='Subtotal de venta (unitario * cantidad)', max_digits=10),
        ),
    ]
