# Generated by Django 5.1.2 on 2026-09-11 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_product_cost_price_product_item_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, default='General', help_text='Departamento o Categoría', max_length=50),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='previous_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Saldo monetario total previo del producto', max_digits=12),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='resulting_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Saldo monetario total resultante del producto', max_digits=12),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Monto monetario del movimiento (quantity * unit_cost)', max_digits=12),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Costo unitario aplicado (CPP o costo de adquisición)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Costo Promedio Ponderado (CPP) o costo de adquisición', max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Precio de venta al público', max_digits=10),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Costo unitario congelado al momento de la venta (CPP)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('SALE', 'Salida por Venta POS'), ('RESTOCK', 'Entrada por Reabastecimiento / Compra'), ('ADJUSTMENT', 'Ajuste Manual'), ('INITIAL', 'Inventario Inicial')], default='SALE', max_length=20),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='previous_stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='resulting_stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
